#import "../../../components/ProjectPreview.gql"
#import "../../../components/Photo.gql"
query ProjectsIndexQuery($startGt: CmsDateTime, $startLt: CmsDateTime!, $take: Float!, $skip: Float!, $where: ShowcaseProjectsWhere, $photosWhere: ShowcasePhotosWhere) {
  cms {
    events(
      where: { startsAt_gte: $startGt, endsAt_lt: $startLt }
      order: startsAt_DESC
    ) {
      items {
        id
        title
        subEventIds
        program {
          webname
        }
      }
    }
  }

  showcase {
    projects (take: $take, skip: $skip, where: $where) {
      ...ProjectPreviewFragment
    }

    photos(take: $take, skip: $skip, where: $photosWhere) {
      ...PhotoFragment
    }
  }
}
