#import "../../../components/ProjectPreview.gql"
#import "../../../components/Photo.gql"

fragment CmsEvents on Query {
  cms {
    events(
      where: { startsAt_gte: $startGt, startsAt_lte: $startLt }
      order: startsAt_DESC
    ) {
      items {
        id
        title
        subEventIds
        program {
          webname
        }
      }
    }
  }
}

fragment ShowcaseProjects on ShowcaseQuery {
  projects (take: $take, skip: $skip, where: $where) {
    ...ProjectPreviewFragment
  }
}

fragment ShowcasePhotos on ShowcaseQuery {
  photos(take: $take, skip: $skip, where: $photosWhere) {
    ...PhotoFragment
  }
}

query ProjectsIndexQuery($startGt: CmsDateTime, $startLt: CmsDateTime!, $take: Float!, $skip: Float!, $where: ShowcaseProjectsWhere) {
  ...CmsEvents
  showcase {
    ...ShowcaseProjects
  }
}

query PhotosIndexQuery($startGt: CmsDateTime, $startLt: CmsDateTime!, $take: Float!, $skip: Float!, $photosWhere: ShowcasePhotosWhere) {
  ...CmsEvents
  showcase {
    ...ShowcasePhotos
  }
}

query ProjectsPhotosIndexQuery($startGt: CmsDateTime, $startLt: CmsDateTime!, $take: Float!, $skip: Float!, $where: ShowcaseProjectsWhere, $photosWhere: ShowcasePhotosWhere) {
  ...CmsEvents
  showcase {
    ...ShowcasePhotos
    ...ShowcaseProjects
  }
}