query GetProjectByIdQuery($id: String!) {
    showcase {
        project(id: $id) {
            name
            members {
                username
            }
            eventGroup {
                title
            }
            region {
                name
            }
        }
    }
}
