#import "../../components/ProjectDetails.gql"

query ProjectByIdQuery ($id: String!) {
  showcase {
    project(id: $id) {
      ...ProjectDetailsFragment
      name
      members {
        username
      }
    }
  }
}
