mutation CreateProjectMutation ($name: String!, $type: ShowcaseProjectType!, $description: String) {
  showcase {
    createProject(project: { name: $name, type: $type, description: $description}) {
      id
    }
  }
}

query CreateProjectAccountLinkedQuery ($username: String!) {
  account {
    getUser(where: { username: $username }, fresh: true ) {
      discordId
    }
  }
}
