mutation CreateProjectMutation ($name: String!, $type: ShowcaseProjectType!, $description: String) {
  showcase {
    createProject(project: { name: $name, type: $type, description: $description}) {
      id
    }
  }
}
