mutation CreateProjectMutation ($name: String!, $type: ShowcaseProjectType!, $description: String) {
  showcase {
    createProject(project: { name: $name, type: $type, description: $description}) {
      id
    }
  }
}

mutation JoinProjectMutation($joinCode: String!) {
  showcase {
    joinProject(joinCode: $joinCode) {
      id
    }
  }
}

query CreateProjectQuery ($id: ID!, $start: ClearDateTime!, $end: ClearDateTime!) {
  account {
    getUser(where: { id: $id }, fresh: true ) {
      discordId
    }
  }
  clear { 
    events(
      where: { startDate:{ lt: $start }, endDate: { gt: $end } },
      orderBy: { startDate: asc }
      take: 25
    ) {
      id
      name
      region {
        name
        webname 
      }
      eventGroup {
        id
        name
        contentfulId
        cmsEventGroup {
          title
          id
        }
      }
    }
  }
}
