#import "../components/ProjectPreview.gql"
query IndexQuery ($startGt: CmsDateTime, $startLt: CmsDateTime!, $take: Float!) {
  cms {
    events(
      where: { startsAt_gte: $startGt, startsAt_lte: $startLt }
      order: startsAt_DESC
    ) {
      items {
        id
        title
        subEventIds
        program {
          webname
        }
      }
    }
  }
  
  showcase {
    projects (take: $take, where: { featured: true }) {
      ...ProjectPreviewFragment
    }
  }
}
