#import "./ProjectMembers.gql"
mutation ProjectMemberAddMutation($projectId: String!, $username: String!) {
  showcase {
    addMember(project: $projectId, username: $username) {
      ...ProjectMembersFragment
    }
  }
}
